name: Deploy to Fly (Dev)

on:
  workflow_dispatch:
  push:
    branches:
      - dev
    paths:
      - website/**.*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Setup fly
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to fly
        run: |
          cd website
          flyctl deploy --remote-only --strategy immediate -c fly.prod.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_DEV }}