name: Deploy to Fly

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - website/**.*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Setup fly
        uses: superfly/flyctl-actions/setup-flyctl@master
      # - name: Deploy convex
      #   run: |
      #     npm install
      #     npx convex deploy
      #   env:
      #     CONVEX_DEPLOY_KEY: ${{ secrets.CONVEX_DEPLOY_KEY }}
      - name: Deploy to fly
        run: flyctl deploy --remote-only --strategy immediate -c fly.prod.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}